daftar_kalimat = [
    "Melaib anak lanang ento",
    "Makeber kedis cenik",
    "Ngeling anak cerik ento",
    "Sirep bapak tiang",
    "Nyakan nasi meme tiang",
    "Ngwacen buku murid rajin ento",
    "Ngajin murid kelas nem gurune ento",
    "Mula padi anak pemacul lingsir",
    "Minum anak cerik ento susu",
    "Nulis Made pesaur tugas",
    "Numbas Okan Biang Dewi sepatu anyar",
    "Nabuh ipun gamelan baleganjur",
    "Dadi guru anak truna ento",
    "Negak motor gede Komang",
    "Wawu mekarya dados staff pegawe punika",
    "Menek kelih panak tiange",
    "Dadi belin tiange ketua STT",
    "Mekarya pegawe nika dados kepala bagian",
    "Dadi Bapak tiange dokter",
    "Maprakara mahasiswa punika dados asisten dosen",
    "Numbasang Adine Wi Ajus buku gambar",
    "Nyeduhang tamiune Biang teh anget",
    "Milih Ajik Koster krama Baline dados gubernur",
    "Ngemaang Putu I Meme bekel masuk",
    "Nyemakang bapa timpalne pancing",
    "Ngalihang bapa sampine padang",
    "Ngurukang Bli Made I Agus nepak kendang",
    "Ngicen tiang I Agus meplalian guli",
    "Sesai Ngai jukung gede bapane di sisin pasih",
    "Ngendingang lagu yowanene di banjar",
    "Nyait wastra pare Istri ring wantilan",
    "Mubut padang pekak tiange di tegal",
    "Ngamah sampi padang ene di tegal",
    "Merayunan Ida nasi ring pewaregan",
    "Ngadol Ia jukut ares di peken",
    "Ngejuk bendegane be gede di pasih",
    "Dadi tunangan Luh Sari uli ibi",
    "Melajah nyetir mobil adine di lapangan",
    "Demen melali I Ketut ka pasih",
    "Engsap melajah adine ibi peteng",
    "Megae Wresa dadi sopir di Denpasar",
    "Melajah tiang ngigel jauk di Sanggar",
    "Nyalon I Kadek dadi perbekel di Desa Sanur",
    "Engsap Made nyampat don di Tegal",
    "Ngainang Bapa I Meme kopi pait di paon",
    "Ngajahang sisia Gurune aksara Bali ring kelas",
    "Nyilihang timpalne I Wayan buku tulis mani tengai",
    "Ngalihang Bapa I Meme saang uli alase",
    "Nawahang pedagang turis kamben ring tongos wisate",
    "Ngalapang petani tamiune buah stroberi di tegal"
]
