daftar_kalimat = [
    "Melaib anak lanang ento",
    "Makeber kedis cenik",
    "Ngeling anak cerik mare lekad",
    "Sirep bapak tiang",
    "Nyakan nasi meme tiang",
    "Ngwacen buku murid rajin ento",
    "Ngajin murid kelas nem gurune",
    "Mula padi anak pemacul lingsir",
    "Minum anak cerik ento susu",
    "Nulis Made pesaur tugas",
    "Numbas Okan Biang Dewi sepatu anyar",
    "Nabuh ipun gamelan baleganjur",
    "Dadi guru anak truna ento",
    "Negak motor gede Komang",
    "Wawu mekarya dados staff pegawe punika",
    "Menek kelih panak tiange",
    "Dadi belin tiange ketua STT",
    "Mekarya pegawe nika dados kepala bagian",
    "Dadi Bapak tiange dokter",
    "Maprakara mahasiswa punika dados asisten dosen",
    "Numbasang Adine Wi Ajus buku gambar",
    "Nyeduhang tamiu Biang teh anget",
    "Milih Ajik Koster krama Bali dados gubernur",
    "Ngemaang Putu Meme bekel",
    "Nyemakang bapa timpalne pancing",
    "Ngalihang bapa sampine padang",
    "Ngurukang Bli Made I Agus nepak kendang",
    "Ngincen tiang I Agus meplalian guli",
    "Ngai jukung bapane di sisin pasih",
    "Ngendingang lagu yowanene di banjar",
    "Nyait wastra pare Istri ring wantilan",
    "Mubut padang pekak di tegal",
    "Ngamah sampi padang di tegal",
    "Merayunan Ida nasi ring pewaregan",
    "Ngadol Ia sayur di peken",
    "Ngejuk bendegane be di pasih",
    "Dadi tunangan Luh Sari uli ibi",
    "Melajah nyetir mobil adine di lapangan",
    "Demen melali I Ketut ka pasih",
    "Engsap melajah adine ibi peteng",
    "Megae Wresa dadi sopir di Denpasar",
    "Melajah tiang ngigel jauk di Sanggar",
    "Nyalon I Kadek dadi perbekel di Desa Sanur",
    "Nu ngainang Bapa I Meme kopi pait di paon",
    "Ngainang Bapa I Meme kopi pait di paon",
    "Ngajahang sisia Gurune aksara Bali ring kelas",
    "Nyilihang timpalne I Wayan buku tulis mani tengai",
    "Ngalihang Bapa I Meme saang uli alase",
    "Nawahang pedagang turisne kamben ring tongos melali",
    "Ngalapang petani tamiune buah stroberi di tegal"
]